name: rybl-dot-net
version: 0.1.0.0
github: "rybla/rybl-dot-net"
license: BSD-3-Clause
author: "Henry Blanchette"
maintainer: "henry@rybl.net"
copyright: "2025 Henry Blanchette"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/rybla/rybl-dot-net#readme>

dependencies:
  - base >= 4.7 && < 5
  - template-haskell
  - bytestring
  - filepath
  - directory
  - text
  - pretty
  - containers
  - list-t
  - transformers
  - mtl
  - lens
  - aeson
  - conduit
  - pandoc
  - pandoc-types
  - doctemplates
  - network-uri
  - http-client
  - http-client-tls
  - http-conduit
  - uri-encode
  - data-default
  - time

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wno-missing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - BlockArguments
  - FlexibleContexts
  - NamedFieldPuns
  - OverloadedRecordDot
  - OverloadedStrings
  - LambdaCase
  - DeriveAnyClass
  - DeriveGeneric
  - StandaloneDeriving
  - TypeApplications

library:
  source-dirs: src

executables:
  rybl-dot-net-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rybl-dot-net

tests:
  rybl-dot-net-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rybl-dot-net
